name="work-internship"
compatibility_date = "2026-02-27"
pages_build_output_dir=".next"
[[d1_databases]]
binding = "DB" 
database_name = "my-database"
database_id = "8d69e0cf-83a9-4b8c-82e8-2b156eb9000b"